### ISSUE TITLE
Expected response

### ISSUE THREAD

**Issue by ibozkurt79** [tarikguney/usa-visa-appointment-checker#1]
Thanks for this great script. What is the expected response ? I am getting default "appointments avaliable" with any generic schedule_id. I was wondering if the response should include earliest available appointment date
Thanks

**Comment by mr0erek** [comment]
> Thanks for this great script. What is the expected response ? I am getting default "appointments avaliable" with any generic schedule_id. I was wondering if the response should include earliest available appointment date Thanks

This script only grep/ matchs the response from the post request by this script.
