### ISSUE TITLE
Add support for Non-Immigrant Visa

### ISSUE THREAD

**Issue by insystic** [tarikguney/usa-visa-appointment-checker#2]
Hi Tarik, Can you please add support for non-immigrant visa applications?

Below are the details:

$loginUrl = "https://ais.usvisa-info.com/en-es/niv/users/sign_in"
$appointmentUrl = "https://ais.usvisa-info.com/en-es/niv/schedule/59141752/payment"
email: dotata6309@eqvox.com
password: ariana.marcus

Would really appreciate your help!

**Comment by tarikguney** [comment]
Hello, this script already is for non-immigrant visa applications. So, you should be fine. If you are having problems, please let me know.

Unfortunately, it does not support immigrant visa applications yet.

**Comment by tarikguney** [comment]
If you don't know how to use it, check out the following screenshot:

<img width="739" alt="image" src="https://github.com/tarikguney/usa-visa-appointment-checker/assets/369188/0d155013-d3c9-4219-af27-a79fdde08124">

The `scheduleId` comes from the URL you pasted in  `$appointmentUrl = "https://ais.usvisa-info.com/en-es/niv/schedule/59141752/payment"`

**Comment by insystic** [comment]
The $loginURL in the PS script is for immigrant applications and doesn´t work for Non-Immigrant applications. Below are the differences in login URL:

IMMIGRANT: $loginUrl = "https://ais.usvisa-info.com/en-tr/**iv**/users/sign_in"
NON-IMMIGRANT: $loginUrl = "https://ais.usvisa-info.com/en-es/**niv**/users/sign_in"

Even, if I change the URL, it doesn´t work correctly.
