### ISSUE TITLE
Check for Earlier Available Appointment Slots

### ISSUE THREAD

**Issue by erengit-tech** [tarikguney/usa-visa-appointment-checker#5]
Currently, the tool checks if there are any available appointment slots. I would like to know if it would be possible to enhance the tool to check if there are any earlier appointment slots available than a specified current appointment date.

**Comment by tarikguney** [comment]
Yes, it’s possible to check that, but it would require making code changes to the script. I’m open to accepting PRs from others. Essentially, this could involve adding a new parameter to the script for comparison. There’s plenty of room for improvement in the script overall.
